// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/maihuabao/cgo/a.go:1:1
package main

/*
extern int* getGoPtr();

static void Main() {
    int* p = getGoPtr();
    *p = 42;
}
*/
import _ "unsafe"

func main() {
	( /*line :14:2*/_Cfunc_Main /*line :14:7*/)()
}

//export getGoPtr
func getGoPtr() * /*line :18:18*/_Ctype_int /*line :18:23*/ {
	return new( /*line :19:13*/_Ctype_int /*line :19:18*/)
}

// func main() {
// 	//values := []int64{42, 9, 101, 95, 88, 27, 25}

// 	values := []string{"42", "9", "101", "95", "88", "27", "25"}
// 	qsort.Sort(values, func(i, j int) bool {
// 		return values[i] < values[j]
// 	})

// 	fmt.Println(values)
// }
